# Generated by Django 2.2 on 2019-04-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadactivitycategory',
            options={'verbose_name_plural': 'Lead activity categories'},
        ),
        migrations.AlterModelOptions(
            name='leadstatuscategory',
            options={'verbose_name_plural': 'Lead status categories'},
        ),
        migrations.AlterField(
            model_name='tenantlead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_leads', to='leads.LeadStatusCategory'),
        ),
    ]
