# Generated by Django 2.2 on 2019-04-14 07:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190414_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantlead',
            name='accomodation_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tenantlead',
            name='space_subtype',
            field=models.CharField(blank=True, choices=[('1-Bed Sharing', '1-Bed Sharing'), ('2-Bed Sharing', '2-Bed Sharing'), ('3-Bed Sharing', '3-Bed Sharing'), ('1-BHK', '1-BHK'), ('2-BHK', '2-BHK'), ('3-BHK', '3-BHK'), ('1-BHK', '1-BHK'), ('2-BHK', '2-BHK'), ('3-BHK', '3-BHK')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenantlead',
            name='space_type',
            field=models.CharField(blank=True, choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=20, null=True),
        ),
    ]
