# Generated by Django 2.2 on 2019-04-14 07:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190414_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantleadactivity',
            options={'verbose_name_plural': 'Tenant lead activities'},
        ),
        migrations.AlterField(
            model_name='houseownerlead',
            name='accomodation_allowed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='houseownerlead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_owner_leads', to='leads.LeadStatusCategory'),
        ),
    ]
