# Generated by Django 2.2 on 2019-04-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_managers', '0001_initial'),
        ('leads', '0004_auto_20190414_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOwnerLeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantLeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_lead_sources', to='leads.LeadSourceCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='houseownerlead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='tenantlead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='houseownerlead',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='houseownerlead',
            name='managed_by',
            field=models.ManyToManyField(blank=True, related_name='managed_house_owner_leads', to='lead_managers.LeadManager'),
        ),
        migrations.RemoveField(
            model_name='tenantlead',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='tenantlead',
            name='managed_by',
            field=models.ManyToManyField(blank=True, related_name='managed_tenant_leads', to='lead_managers.LeadManager'),
        ),
        migrations.DeleteModel(
            name='LeadSource',
        ),
        migrations.AddField(
            model_name='tenantleadsource',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='leads.TenantLead'),
        ),
        migrations.AddField(
            model_name='houseownerleadsource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_owner_lead_sources', to='leads.LeadSourceCategory'),
        ),
        migrations.AddField(
            model_name='houseownerleadsource',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='leads.HouseOwnerLead'),
        ),
    ]
