# Generated by Django 2.2 on 2019-04-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20190416_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsourcecategory',
            options={'verbose_name_plural': 'Lead source categories'},
        ),
        migrations.AlterField(
            model_name='houseownerleadsource',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenantleadsource',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
