# Generated by Django 2.2 on 2019-04-18 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadstatuscategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerleadactivity',
            name='post_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_status_house_owner_lead_activities', to='leads.LeadStatusCategory'),
        ),
        migrations.AddField(
            model_name='houseownerleadactivity',
            name='pre_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_status_house_owner_lead_activities', to='leads.LeadStatusCategory'),
        ),
        migrations.AddField(
            model_name='tenantleadactivity',
            name='post_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_status_tenant_lead_activities', to='leads.LeadStatusCategory'),
        ),
        migrations.AddField(
            model_name='tenantleadactivity',
            name='pre_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_status_tenant_lead_activities', to='leads.LeadStatusCategory'),
        ),
    ]
