# Generated by Django 2.2 on 2019-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20190418_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerleadactivity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantleadactivity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
