# Generated by Django 2.2 on 2019-04-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20190418_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatuscategory',
            name='level',
        ),
    ]
