# Generated by Django 2.2 on 2019-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20190713_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerlead',
            name='referral_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantlead',
            name='referral_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
