# Generated by Django 2.2 on 2019-08-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20190713_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerlead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houseownerlead',
            name='zoho_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantlead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantlead',
            name='zoho_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
