# Generated by Django 2.2 on 2019-08-10 06:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20190808_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseownerlead',
            name='accomodation_allowed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family'), ('Couple', 'Couple')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tenantlead',
            name='accomodation_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family'), ('Couple', 'Couple')], max_length=25, null=True),
        ),
    ]
