# Generated by Django 2.2 on 2019-08-10 08:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20190810_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseownerleadhouseaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='houseownerleadpermanentaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantleadpermanentaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantleadpreferredlocationaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='houseownerlead',
            name='accomodation_allowed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family'), ('couple', 'Couple')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tenantlead',
            name='accomodation_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('family', 'Family'), ('couple', 'Couple')], max_length=25, null=True),
        ),
    ]
