# Generated by Django 2.2 on 2019-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20190810_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantlead',
            name='space_subtype',
            field=models.CharField(blank=True, choices=[('1-Bed Sharing', '1-Bed Sharing'), ('2-Bed Sharing', '2-Bed Sharing'), ('3-Bed Sharing', '3-Bed Sharing'), ('1-BHK', '1-BHK'), ('2-BHK', '2-BHK'), ('3-BHK', '3-BHK'), ('1-RK', '1-RK'), ('1-BHK', '1-BHK'), ('2-BHK', '2-BHK'), ('3-BHK', '3-BHK')], max_length=20, null=True),
        ),
    ]
