# Generated by Django 2.2 on 2019-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_managers', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmanager',
            name='zoho_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
