AFFILIATE_TOOL_BACKEND_BASE_URL = 'https://affiliate.halanx.com'
TENANT_LEAD_REFERRAL_UPDATE_URL = AFFILIATE_TOOL_BACKEND_BASE_URL + '/api/tenant/referrals/{pk}/'
HOUSE_OWNER_LEAD_REFERRAL_UPDATE_URL = AFFILIATE_TOOL_BACKEND_BASE_URL + '/api/owner/referrals/{pk}/'
